# config/packages/doctrine/Car.orm.yaml

App\Entity\Car:
  type: entity
  table: car
  id:
    id:
      type: integer
      generator:
        strategy: auto
  fields:
    mileage:
      type: integer
    dateCreation:
      type: datetime
    price:
      type: float
    modele:
      type: string
      length: 50
  manyToMany:
    is_equipped:
      targetEntity: App\Entity\Equipment
      mappedBy: cars
  oneToMany:
    car_equipment:
      targetEntity: App\Entity\Equipment
      mappedBy: car
  lifecycleCallbacks: {}
