vich_uploader:
  db_driver: orm

<<<<<<< HEAD
  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/public/images"
=======
  mappings:
    products:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/public/images/products"
>>>>>>> 512ad8a1f7622083cc6621835ce331f4ff9c93ae
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
