index:
  path: /
  controller: App\Controller\HomeController::index

# ---------------- Routes Car -------------------

car:
  path: /car
  controller: App\Controller\CarController::index

car_display:
  path: /car/{id}
  controller: App\Controller\CarController::display

# ---------------- Routes services -------------------

app_services_index:
  path: "/services/"
  controller: App\Controller\ServicesController::index

app_services_new:
  path: /services/new
  controller: App\Controller\ServicesController::new

app_services_show:
  path: /services/{id}
  controller: App\Controller\ServicesController::show

app_services_edit:
  path: /services/{id}/edit
  controller: App\Controller\ServicesController::edit

app_services_delete:
  path: /services/{id}
  controller: App\Controller\ServicesController::delete

# ---------------- Routes reviews -------------------

app_reviews_index:
  path: "/reviews"
  controller: App\Controller\ReviewsController::index

app_reviews_new:
  path: "/reviews/new"
  controller: App\Controller\ReviewsController::new

app_reviews_show:
  path: "/reviews/show"
  controller: App\Controller\ReviewsController::show

# ------------------- Routes contact---------------

app_contact:
  path: /contact
  methods: ["GET"]
  requirements:
    getModele: '\w+'
  controller: App\Controller\ContactController::index
