index:
  path: /
  controller: App\Controller\HomeController::index

car:
  path: /car
  controller: App\Controller\CarController::index

car_create:
  path: /car/create
  controller: App\Controller\CarController::create

car_display:
  path: /car/{id}
  controller: App\Controller\CarController::display

car_update:
  path: /car/{id}/update
  controller: App\Controller\CarController::update

car_delete:
  path: /car/{id}/delete
  controller: App\Controller\CarController::delete
